# -*- coding: utf-8 -*-
"""hellow.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Wgp5-MEnodeUyHq_IcqSV76EMT7pKV6
"""

with open("/content/hello.py", "w") as f:
    f.write("""
import streamlit as st

def main():
    st.title("Hello, Streamlit!")
    st.write("Welcome to Streamlit Cloud.")

if __name__ == "__main__":
    main()
    """)